# Titel und Beschreibung Ihrer Seite
title: md-toc
description: 

# Theme: Just the Docs
remote_theme: just-the-docs/just-the-docs

url: "https://gem-cp.github.io"
baseurl: "/md-toc"

# Logo

logo: "/images/md-toc-logo.png"
favicon_ico: "/images/md-toc-logo.png"

search_enabled: true
